- python
  - python is a programing paradism means it supports functional porgraming and object oriented programing and also works with procedure orineted programing  
- procedure oriented language
  - procedure oriented means write our programing language using funtion and object and clases
- object oriented launguage
  - object:realme world entity or it is a physically entity represented memory
  - class:logical entity contains logic of the appilication

In [ ]:
class class_name:
    variables
    methods or functions

In [1]:
print("hi hello")

hi hello


In [2]:
8+9

17

In [1]:
class Hi:
    a=23
    b=32
    name="ssbsc"
    def show():
        print("iam sai show() function")

In [3]:
Hi.name

'ssbsc'

In [4]:
Hi.show()

iam sai show() function


In [5]:
print(Hi.a,Hi.b)

23 32


In [6]:
Hi.b

32

In [7]:
Hi.a

23

In [9]:
class Hi:
    name="ssbsc"
    program_name='python'
    def display():
        print("iam sai display function()")
    def show():
        print("iam sai show function()")
print(Hi.name,Hi.program_name)
print(Hi.display())

ssbsc python
iam sai display function()
None


In [11]:
print(Hi.display())

iam sai display function()
None


In [12]:
        def display():
        print("iam sai display function()")
        return("iam sai return statement")
    def show():
        print("iam sai show function()")
print(Hi.name,Hi.program_name)
print(Hi.display())
print(Hi.show())

ssbsc python
iam sai display function()
None
iam sai show function()
None


In [15]:
class Hello():
    def display():
        print("iam sai display function()")
        return("iam sai return statement")
    def show():
        print("iam sai show function()")

print(Hello.display())
print(Hello.show())

iam sai display function()
iam sai return statement
iam sai show function()
None


In [ ]:
# in java object declaration:
  # class_name object_name=new_classname
# In python
  # obj_name=classname
    

In [19]:
class Hi:
    name="ssbsc"
    program_name='python'
    def display(self):
        print("iam sai display function()")
        return("iam sai return statement")
    def show():
        print("iam sai show function()")
obj=Hi()
print(obj.name,obj.program_name)
print(obj.display())

ssbsc python
iam sai display function()
iam sai return statement


## Constructor
- Constructor:without using object we will call mehtods
  - in java:class name should be name as same name
  - in python:we will use one special method to define 
  - __init(self)__

In [17]:
class Hai:
    def __inti__(self,name,roll_no):
        self.name=name
    self.roll_no=roll_no
        print("hi",self.name)
        def display(self):
        print("your roll_no",self.roll_no)
obj=Hai('sai','21A85A0604')
obj.display()

IndentationError: unexpected indent (Temp/ipykernel_3284/2065258591.py, line 5)

## inheritence
- inherits something parent class to child clss

In [ ]:
class A:
    3a,b=23,32
class B:
    #c,d=46,64

In [5]:
class A:
    a,b=23,32
    def msg():
        print("iam sai class A")
class B(A):
    c,d=46,64
    def msg1():
        print("iam sai class A")
obj=B
print(obj.c,obj.a)
obj.msg1()
obj.msg()


46 23
iam sai class A
iam sai class A


## Python libraries for data science
- organizing,processing,analysing the huge amount data
- apply data visualization
- extracting the data from the source
- nearly 20 python libraries are there
### Top
- Numpy
- Panda
- Matplotlib

#### Numpy
- Numpy::(numpy) means numerical data+python
- it is fundamental package for scinetific compution in python 
- numpy is python library
- it is to create multidimentional array for fast operations
   - its dealing with mathemetical,scientific,statical data
- numpy contains a powerfull n-dimentional array object which in the form of rows and columns
- we can initilize numpy arrays from nested python list

In [ ]:
# how to install numpy
 - pip install numpy

In [ ]:
# how to import and use numpy pakage
 import numpy as np

In [5]:
#how to find numpy version
np.__version__

'1.20.3'

In [3]:
# how to create numpy arrays
import numpy as np
a=np.array([1,2,3,4])# single dimentional array
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [12]:
a2=np.array([[2,3,4],[5,6,7]])
print(a2)
print(type(a2))

[[2 3 4]
 [5 6 7]]
<class 'numpy.ndarray'>


In [14]:
# to know about the shape of the array
a2.shape

(2, 3)

In [15]:
li=[2,3,4,'h','i']
print(type(li))
a1=np.array(li)
print(a1)
print(type(a1))

<class 'list'>
['2' '3' '4' 'h' 'i']
<class 'numpy.ndarray'>


In [17]:
ar=np.array([[1,2],[3,4],[5,6]])
print(ar)

[[1 2]
 [3 4]
 [5 6]]


In [18]:
print(ar.dtype)

int32


In [19]:
b=np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


In [20]:
print(b.shape)

(2, 2)


In [21]:
b.itemsize

4

In [23]:
b.ndim

2

In [24]:
#range
a=np.array(range(23))
print(a)
print(type(a))
print(a.shape)
print(a.size)
b=np.array(range(21,23,22))
print(b)
print(b.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]
<class 'numpy.ndarray'>
(23,)
23
[21]
1


In [16]:
#arange()-third party of of numpy library
a=np.arange(23)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

In [15]:
a=np.arange(1,20,3)
a

array([ 1,  4,  7, 10, 13, 16, 19])

In [14]:
x=np.arange(10)
print(x.reshape(5,2))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [13]:
#reshape of array
a1=np.array([1,2,3,4,5,6,7,8])
print(a1.shape)
print("before reshape",a1)
print(a1.ndim)
a2=a1.reshape(4,2)
print("after reshape",a2)
print(a2.shape)
print(a2.ndim)

(8,)
before reshape [1 2 3 4 5 6 7 8]
1
after reshape [[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)
2


In [19]:
# resize of array (its modifies shape and array)
a1=np.array([1,2,3,4,5,6,7,8,])
print(a1)
print(a1.shape)
a1.resize(3)# resize the no of elements from original
print(a1)
print(a1.shape)
a1.resize(2,4)
print(a1)
print(a1.shape)
a1.resize(3,3)
print(a1)
print(a1.shape)

[1 2 3 4 5 6 7 8]
(8,)
[1 2 3]
(3,)
[[1 2 3 0]
 [0 0 0 0]]
(2, 4)
[[1 2 3]
 [0 0 0]
 [0 0 0]]
(3, 3)


In [11]:
# zero array
import numpy as np
a1=np.zeros(3)
a2=np.zeros((2,4),dtype="int64")
print(a1.dtype)
print(a2.dtype)
print(a1)
print(a2)


float64
int64
[0. 0. 0.]
[[0 0 0 0]
 [0 0 0 0]]


In [21]:
# one array
a2=np.ones(3,dtype="int64")
print(a2)
np.ones((6,5),dtype="int64")

[1 1 1]


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [22]:
# full array- full(dimentions,specified number)
a=np.full((3,3),7)
a

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [23]:
np.diag(a)

array([7, 7, 7])

In [26]:
np.full(3,100)

array([100, 100, 100])

In [25]:
np.full((3,9),500)

array([[500, 500, 500, 500, 500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500, 500, 500, 500, 500]])

In [30]:
# eye array
np.eye(6,dtype="int64")

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]], dtype=int64)

In [33]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
np.diag()

TypeError: _diag_dispatcher() missing 1 required positional argument: 'v'

In [37]:
r=np.random.randint(1,10)
r

6

In [38]:
s=np.random.randint(1,19,12).reshape(3,4)
s

array([[ 6,  1, 18, 18],
       [15, 12, 13, 15],
       [16, 12, 13, 14]])

In [42]:
p=np.random.random((6)).reshape(2,3)
p

array([[0.48883504, 0.34891373, 0.58813093],
       [0.51545599, 0.33061617, 0.06952013]])

In [43]:
f=np.random.randn(2,3)
f

array([[-0.44001232,  1.41777551,  0.19284374],
       [-0.31575785, -0.52435282, -0.12203451]])

In [45]:
s=np.random.randint(2,30),(10,2)
s

(16, (10, 2))

In [44]:
a[1:5]

array([[7, 7, 7],
       [7, 7, 7]])

In [46]:
a[2:,:2]

array([[7, 7]])

In [47]:
a>10

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [48]:
a[a>10]

array([], dtype=int32)

In [49]:
a

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [50]:
a[a>10].sum()

0

In [52]:
a.max()

7

In [53]:
a.min()

7

In [54]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [57]:
b=np.arange(10,19).reshape(3,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [58]:
print(a+b)
print("******************")
print(a-b)
print("________")
print(a*b)
print("$$$$$$$$$$$$$$$$$4")
print(a%b)
print(np.max(a))
print(np.min(b))


[[10 12 14]
 [16 18 20]
 [22 24 26]]
******************
[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]
________
[[  0  11  24]
 [ 39  56  75]
 [ 96 119 144]]
$$$$$$$$$$$$$$$$$4
[[0 1 2]
 [3 4 5]
 [6 7 8]]
8
10


In [59]:
# 0 to 15---->(3,5)
a=np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [60]:
print(np.mean(a))

7.0


In [61]:
print(np.median(a))

7.0


In [62]:
b.dot(a)

array([[175, 208, 241, 274, 307],
       [220, 262, 304, 346, 388],
       [265, 316, 367, 418, 469]])

In [63]:
np.log([1,2,3])

array([0.        , 0.69314718, 1.09861229])

In [68]:
a+3

array([[ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17]])

In [69]:
a+10

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [70]:
np.exp(1)

2.718281828459045

In [71]:
np.sin(60)

-0.3048106211022167

In [72]:
np.sin(30)

-0.9880316240928618

In [67]:
np.tan(30)

-6.405331196646276

In [73]:
np.cos(60)

-0.9524129804151563

In [74]:
import numpy
dir(numpy)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',

## Panda s
- pandas is the data science package
- it is used for
  - data manulpilation (modification and updatations)
  - data analysis
  - data cleaning(to remove unwanted data or unnecessary data)
- contains mainly 2 data structures in pandas
  - series-----sequence of a data
  - data frames----data with row & column